---
version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install curl -y
      - apt-get install jq -y 
      - pip install awscli
      - gem install roadworker
  pre_build:
    commands:
      - curl -qL -o aws_credentials.json 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI > aws_credentials.json
      - aws configure set region $AWS_REGION
      - aws configure set aws_access_key_id `jq -r '.AccessKeyId' aws_credentials.json`
      - aws configure set aws_secret_access_key `jq -r '.SecretAccessKey' aws_credentials.json`
      - aws configure set aws_session_token `jq -r '.Token' aws_credentials.json`
      - cd $CODEBUILD_SRC_DIR_Routefile
      - roadwork -a --dry-run
  build:
    commands:
      - roadwork -a
  post_build:
    commands:
      - echo "ビルドが完了しました。"